CC=gcc
CFLAG=-std=gnu99 -Wall -Werror -pedantic

#step3: step3.c
#	$(CC) -o step3 step3.c $(CFLAG) 

step2: step2.c
	$(CC) -o step2 step2.c $(CFLAG) 

#step1: step1.c
#	$(CC) -o step1 step1.c $(CFLAG) 
